# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_auto_20151206_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='flow_thresh_max',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='flow_thresh_min',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='max_sessions_per_day',
        ),
    ]
