# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_auto_20160520_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meet',
            options={'ordering': ('-is_current_meet', 'name'), 'verbose_name': 'Meet', 'verbose_name_plural': 'Meets'},
        ),
    ]
