# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_auto_20160916_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='enable_ranking',
        ),
    ]
