# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_remove_meet_enable_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='all_last_place_ties_in_awards',
            field=models.BooleanField(default=False),
        ),
    ]
