# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0012_meet_enable_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='host',
            field=models.CharField(default='', max_length=200),
        ),
    ]
