# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0014_auto_20170824_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='enable_ranking',
            field=models.BooleanField(default=False, help_text='scoring is live, gymnast and team ranks are adjusting as new scores come in.', verbose_name='Ranking'),
        ),
    ]
