# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0015_auto_20170827_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFairplayMeetArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Import a Fairplay meet from an archive of exported backup files', max_length=200, null=True, upload_to='', verbose_name='File')),
            ],
            options={
                'verbose_name_plural': '',
            },
        ),
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Meet Date'),
        ),
    ]
