# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0016_auto_20171011_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importfairplaymeetarchive',
            options={'managed': False, 'verbose_name_plural': ''},
        ),
    ]
