# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20160913_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymnast',
            name='jdo',
        ),
    ]
