# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20160915_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='group',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
