# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_level_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
