# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20160915_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymnast',
            name='registration',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team',
        ),
    ]
