# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20160916_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnast',
            name='per_gymnast_cost',
            field=models.PositiveSmallIntegerField(default=90, null=True, verbose_name='Price Per Gymnast'),
        ),
        migrations.AddField(
            model_name='team',
            name='gymnast_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total Gymnast Cost'),
        ),
        migrations.AddField(
            model_name='team',
            name='per_team_award_cost',
            field=models.PositiveSmallIntegerField(default=50, null=True, verbose_name='Price Per Team Award'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_award_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Team Award Cost'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total Owed'),
        ),
    ]
