# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_auto_20160916_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gymnasts', to='competition.Division', verbose_name='Age division'),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gymnasts', to='registration.Level'),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='per_gymnast_cost',
            field=models.PositiveSmallIntegerField(default=90, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gymnasts', to='registration.ShirtSize'),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='starting_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_gymnasts', to='competition.Event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='per_team_award_cost',
            field=models.PositiveSmallIntegerField(default=50, null=True, verbose_name='Team Award Cost'),
        ),
    ]
