# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20160918_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(help_text='ex. Fairland', max_length=100),
        ),
    ]
