# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_auto_20161014_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnast',
            name='discipline',
            field=models.CharField(blank=True, choices=[('mag', 'Mens Artistic'), ('wag', 'Womens Artistic')], max_length=20, null=True),
        ),
    ]
