# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_gymnast_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='discipline',
            field=models.CharField(choices=[('mag', 'Mens Artistic'), ('wag', 'Womens Artistic')], max_length=20, null=True),
        ),
    ]
