# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-17 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_auto_20170816_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymnastnotes',
            options={'ordering': ['-note__created'], 'verbose_name': 'Gymnast Note', 'verbose_name_plural': 'Gymnast Notes'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created'], 'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='teamnotes',
            options={'ordering': ['-note__created'], 'verbose_name': 'Team Note', 'verbose_name_plural': 'Team Notes'},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='date',
            new_name='created',
        ),
    ]
