# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-17 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_auto_20170816_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='meet',
        ),
        migrations.AlterModelOptions(
            name='gymnastnotes',
            options={'verbose_name': 'Gymnast Note', 'verbose_name_plural': 'Gymnast Notes'},
        ),
        migrations.AlterModelOptions(
            name='teamnotes',
            options={'verbose_name': 'Team Note', 'verbose_name_plural': 'Team Notes'},
        ),
        migrations.AddField(
            model_name='gymnastnotes',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymnastnotes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 16, 22, 47, 26, 757429)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamnotes',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamnotes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 16, 22, 47, 38, 911408)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymnastnotes',
            name='note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teamnotes',
            name='note',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
