# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0013_auto_20170816_1349'),
        ('registration', '0037_auto_20170816_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Cost')),
                ('paid', models.DateField(help_text='Date on the check, bank transfer, etc.')),
                ('detail', models.CharField(blank=True, help_text='Check #, transfer confirmation #, how was delivered or to whom, etc.', max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='meet.Meet')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.Team')),
            ],
            options={
                'verbose_name': 'Payments',
                'ordering': ['paid'],
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
