# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['paid'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='paid_in_full',
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter a negative number for a refund', max_digits=6, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid',
            field=models.DateField(help_text='Date on the check, bank transfer, etc.', verbose_name='Date'),
        ),
    ]
