# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_importusagreservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importusagreservation',
            options={'verbose_name_plural': ''},
        ),
        migrations.AddField(
            model_name='importusagreservation',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a USAG reservation', max_length=200, null=True, upload_to='', verbose_name='File'),
        ),
    ]
