# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_auto_20170828_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtsize',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
