# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20171012_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='notes',
            field=models.TextField(blank=True, help_text='May be exposed in CSV data exports.', null=True, verbose_name='Public Notes'),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='notes',
            field=models.TextField(blank=True, help_text='May be exposed in CSV data exports.', null=True, verbose_name='Public Notes'),
        ),
        migrations.AlterField(
            model_name='gymnastnotes',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamnotes',
            name='note',
            field=models.TextField(),
        ),
    ]
