# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_auto_20160520_2229'),
        ('registration', '0018_auto_20151228_1215'),
        ('competition', '0027_auto_20151228_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymnastEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymnasts', to='competition.Event')),
            ],
            options={
                'ordering': ['gymnast', 'event'],
            },
        ),
        migrations.CreateModel(
            name='TeamAwardRankEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event_rankings', to='competition.Event')),
                ('gymnast_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event_rankings', to='competition.GymnastEvent')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event_rankings', to='meet.Meet')),
            ],
            options={
                'verbose_name': 'Team Award Rank Athlete Event',
                'verbose_name_plural': 'Team Award Rank Athlete Events',
            },
        ),
        migrations.AlterUniqueTogether(
            name='athleteevent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='athleteevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='athleteevent',
            name='gymnast',
        ),
        migrations.RemoveField(
            model_name='teamawardrankathleteevent',
            name='athlete_event',
        ),
        migrations.RemoveField(
            model_name='teamawardrankathleteevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='teamawardrankathleteevent',
            name='team_award_rank',
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.CreateModel(
            name='Gymnast',
            fields=[
            ],
            options={
                'proxy': True,
                'ordering': ('athlete_id', 'last_name', 'first_name'),
            },
            bases=('registration.gymnast',),
        ),
        migrations.AddField(
            model_name='teamawardrank',
            name='meet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_ranks', to='meet.Meet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AthleteEvent',
        ),
        migrations.DeleteModel(
            name='TeamAwardRankAthleteEvent',
        ),
        migrations.AddField(
            model_name='teamawardrankevent',
            name='team_award_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event_rankings', to='competition.TeamAwardRank'),
        ),
        migrations.AddField(
            model_name='gymnastevent',
            name='gymnast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registration.Gymnast'),
        ),
        migrations.AddField(
            model_name='gymnastevent',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymnast_events', to='meet.Meet'),
        ),
        migrations.AlterUniqueTogether(
            name='gymnastevent',
            unique_together=set([('gymnast', 'event')]),
        ),
    ]
