# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_auto_20160520_2229'),
        ('competition', '0028_auto_20160912_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledsign',
            name='meet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='meet.Meet'),
            preserve_default=False,
        ),
    ]
