# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0030_auto_20160915_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_sart',
            new_name='session_start',
        ),
    ]
