# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0031_auto_20160915_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='warmup',
            field=models.CharField(choices=[('Traditional', 'Traditional'), ('Warm-up/Compete', 'Warm-up/Compete')], default='Traditional', max_length=25, verbose_name='Session Flow'),
        ),
    ]
