# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0032_auto_20160915_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['level', 'min_age'], 'verbose_name': 'Age Division', 'verbose_name_plural': 'Age Divisions'},
        ),
    ]
