# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0033_auto_20160915_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamawardrank',
            options={'verbose_name': 'Team Awards > Rank > Score', 'verbose_name_plural': 'Team Awards > Rank > Score'},
        ),
        migrations.AlterModelOptions(
            name='teamawardrankevent',
            options={'verbose_name': 'Team Awards > Rank > Event > Gymnast', 'verbose_name_plural': 'Team Awards > Rank > Event > Gymnast'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='warmup_start',
        ),
        migrations.AddField(
            model_name='session',
            name='open_warmup_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Open Warmup Start Time'),
        ),
        migrations.AddField(
            model_name='session',
            name='timed_warmup_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Timed Warmup Start Time'),
        ),
    ]
