# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_auto_20161014_1906'),
        ('meet', '0009_auto_20160916_1200'),
        ('competition', '0034_auto_20160920_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRankEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx', models.FloatField(blank=True, null=True)),
                ('fx_rank', models.PositiveSmallIntegerField(null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('ph_rank', models.PositiveSmallIntegerField(null=True)),
                ('sr', models.FloatField(blank=True, null=True)),
                ('sr_rank', models.PositiveSmallIntegerField(null=True)),
                ('vt', models.FloatField(blank=True, null=True)),
                ('vt_rank', models.PositiveSmallIntegerField(null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('pb_rank', models.PositiveSmallIntegerField(null=True)),
                ('hb', models.FloatField(blank=True, null=True)),
                ('hb_rank', models.PositiveSmallIntegerField(null=True)),
                ('ub', models.FloatField(blank=True, null=True)),
                ('ub_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('b_rank', models.PositiveSmallIntegerField(null=True)),
                ('aa', models.FloatField(blank=True, null=True)),
                ('aa_rank', models.PositiveSmallIntegerField(null=True)),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='registration.Gymnast')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='meet.Meet')),
            ],
        ),
        migrations.AlterField(
            model_name='teamaward',
            name='levels',
            field=models.ManyToManyField(related_name='team_awards', to='registration.Level'),
        ),
        migrations.AlterUniqueTogether(
            name='scorerankevent',
            unique_together=set([('gymnast', 'meet')]),
        ),
    ]
