# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0036_auto_20161014_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensArtisticGymnast',
            fields=[
            ],
            options={
                'proxy': True,
                'ordering': ('athlete_id', 'last_name', 'first_name'),
            },
            bases=('competition.gymnast',),
        ),
        migrations.AlterField(
            model_name='scorerankevent',
            name='gymnast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='registration.Gymnast'),
        ),
    ]
