# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_gymnast_discipline'),
        ('competition', '0037_auto_20161014_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensArtisticGymnast',
        ),
        migrations.CreateModel(
            name='MensArtisticGymnast',
            fields=[
                ('gymnast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.Gymnast')),
            ],
            options={
                'verbose_name_plural': 'Mens Artistic Event Gymnasts',
                'verbose_name': 'Gymnast',
            },
            bases=('competition.gymnast',),
        ),
    ]
