# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0038_auto_20161014_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensartisticgymnast',
            name='gymnast_ptr',
        ),
        migrations.DeleteModel(
            name='MensArtisticGymnast',
        ),
    ]
