# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-26 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0044_auto_20161020_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnastevent',
            name='place',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
