# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-26 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0045_gymnastevent_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymnastevent',
            options={'ordering': ['gymnast', 'event'], 'verbose_name': 'Gymnast > Rank > Place', 'verbose_name_plural': 'Gymnast > Rank > Place'},
        ),
    ]
