# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0046_auto_20161126_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymnastevent',
            options={'ordering': ['gymnast', 'event'], 'verbose_name': 'Gymnast Event', 'verbose_name_plural': 'Gymnast Events > Rank > Score > Place'},
        ),
        migrations.AlterField(
            model_name='teamawardrank',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_ranks', to='registration.Team'),
        ),
        migrations.AlterField(
            model_name='teamawardrank',
            name='team_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_ranks', to='competition.TeamAward'),
        ),
    ]
