# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0047_auto_20161202_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaward',
            name='award_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of places team awards will go out to'),
        ),
    ]
