# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0048_auto_20170816_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True, help_text='Event is included as part of this meet'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_mag',
            field=models.BooleanField(default=True, help_text="Men's Artistic Gymnastics Event", verbose_name='Is MAG?'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_wag',
            field=models.BooleanField(default=True, help_text="Women's Artistic Gymnastics Event", verbose_name='Is MAG?'),
        ),
    ]
