# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0049_auto_20170824_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='meet',
        ),
        migrations.AlterField(
            model_name='event',
            name='is_mag',
            field=models.BooleanField(default=True, help_text="Men's Artistic Gymnastics Event", verbose_name='MAG'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_wag',
            field=models.BooleanField(default=True, help_text="Women's Artistic Gymnastics Event", verbose_name='WAG'),
        ),
    ]
