# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0050_auto_20170824_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledshow',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='ledsign',
            name='meet',
        ),
        migrations.AlterUniqueTogether(
            name='ledsign',
            unique_together=set([('name', 'device')]),
        ),
    ]
