# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0051_auto_20170921_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='registration.Level'),
        ),
    ]
