# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0053_auto_20170921_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.LEDSign'),
        ),
        migrations.AlterField(
            model_name='teamaward',
            name='levels',
            field=models.ManyToManyField(related_name='team_awards', to='registration.Level'),
        ),
    ]
