# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0054_auto_20170923_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='divisions',
            field=models.ManyToManyField(blank=True, help_text='\n        Select from the list on the left which age divisions will compete in this session.\n        All gymnasts in the selected age division will be automatically assigned to this session.\n        Age divisions may not be split across multiple sessions.', related_name='session', to='competition.Division'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(help_text='Session 1, Session 2, etc.', max_length=255),
        ),
    ]
